Myproject2/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from todo.views import home, todolist

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home,name="home"), #configuring views.py function with project
    url(r'^todos/$',todolist, name="todolist"), #configuring views.py function with project
    url(r'^todos/', include("todo.urls", namespace="todo"))
]

todo/urls.py
from django.conf.urls import url
from todo.views import todoadd,todolist,contact,about,todoedit,tododelete


urlpatterns=[
    url(r'^$', todolist, name="todolist"),
    url(r'^add$', todoadd, name="todoadd"),
    url(r'^contact/$',contact,name="contact"),
    url(r'^about/$', about, name="about"),
    url(r'^edit/(?P<pk>\d+)/$', todoedit, name="todoedit"),
    url(r'^delete/(?P<pk>\d+)/$', tododelete, name="tododelete")
]

todo/models.py
from django.db import models
#Create your models here.
class Todo(models.Model):
    Title=models.CharField(max_length=255)
    name=models.CharField(max_length=50)
    email=models.CharField(max_length=20)
    mobile=models.CharField(max_length=20)
    description=models.CharField(max_length=255)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

class Contact(models.Model):  
    name=models.CharField(max_length=100)
    email=models.CharField(max_length=100)
    mobile=models.CharField(max_length=100)
    message=models.TextField()  

todo/forms.py
from django import forms
from todo.models import Todo,Contact
class TodoForm(forms.ModelForm):
    class Meta:
        model=Todo
        fields={"title","name","email","mobile","description"}


class ContactForm(forms.ModelForm):
    class Meta:
        model=Contact
        fields={"name","email","mobile","message"}

todo/views.py
from django.shortcuts import render,redirect,get_object_or_404
from todo.forms import TodoForm,ContactForm #importing forms from forms.py
from todo.models import Todo #configuring models.py and views.py

# Create your views here.

def home(request):
    return render(request,'home.html')
#inserting the values from forms.py to database

def todoadd(request):
    todoform=TodoForm(request.POST or None)
    if todoform.is_valid():
        todoform.save()
        return redirect("todolist")
    return render(request,'todoadd.html',{'forms':todoform})


def todolist(request):
    allfeedback=Todo.objects.all()
    return render(request,'todolist.html',{'all':allfeedback})

def contact(request):
    contactform=ContactForm(request.POST or None)
    if contactform.is_valid():
        contactform.save()
        return redirect("home")
    return render(request,'contact.html',{'forms':contactform})

def about(request):
    return render(request,'about.html')

def todoedit(request,pk):
    todo=get_object_or_404(Todo,pk=pk)
    todoform=TodoForm (request.POST or None, instance=todo)
    if todoform.is_valid():
        todoform.save()
        return redirect("todolist")
    return render (request,'todoadd.html', {'forms': todoform})

def tododelete(request,pk):
    todo=get_object_or_404(Todo,pk=pk)
    if request.method=="POST":
        todo.delete()
        return redirect("todolist") 
    return render(request,'tododelete.html',{'todo':todo})     

templates/about.html
{% extends "base.html" %}
{% block content %}
<h1>About Page</h1>
{%endblock%}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>
    {%block content%}

    {%endblock%}
</body>
</html>

templates/contact.html
{% extends "base.html" %}
{%block content %}
<form method="post">
<h1>Contact Page</h1>
{%csrf_token%}
{{forms.as_p}}
<button type="submit">submit</button>
</form>
{%endblock%}

templates/footer.html
{% extends 'base.html' %}
{% block content %}
<h1>Footer Page</h1>
{%endblock%}

templates/home.html
{% extends "base.html" %}
{%block content %}
<h1>Home Page</h1>
{%endblock%}

templates/navbar.html
<h1>Navbar Page</h1>

templates/todoadd.html
{% extends "base.html" %}
{%block content %}
<h1>todo Page</h1>
<div>
    <form method="POST">
        <h1>Add Your Valueable Feedback</h1>
        {%csrf_token%}
        {{forms.as_p}}
        <button type="submit">Submit your Feedback</button>
    </form>
</div>
{%endblock%}

templates/tododelete.html
{%extends 'base.html'%}
{%block content%}
<form method="post">
<h1>Are you sure?</h1>
<p> Are you sure you want to delete "{{todo.title}}"? All of the following objects and their</p>
{%csrf_token%}
<button type="submit" name="tododelete">Delete Your Review</button>
</form>

{%endblock%}

templates/todolist.html
{% extends "base.html" %}
{%block content %}
<h1>Todolist Page</h1>
<table>
    <thead>
        <tr>
            <th>title</th>
            <th>name</th>
            <th>email</th>
            <th>mobile</th>
            <th>description</th>
         </tr>
        
    </thead>

    <tbody>

        {%for todo in all%}
        <tr>
            
            <td>{{todo.title}}</td>
            <td>{{todo.name}}</td>
            <td>{{todo.email}}</td>
            <td>{{todo.mobile}}</td>
            <td>{{todo.description}}</td>
            <td>{{todo.create_at}}</td>
            <td>{{todo.updated_at}}</td>

            <td>
            <a href="{%url 'todo:todoedit' todo.id%}">
                <button>update</button>
            </a>

            <a href="{%url 'todo:tododelete' todo.id%}">
                <button>Delete</button>
            </a>
            </td>   
        </tr>
        {%endfor%}
    </tbody>
</table>
{%endblock%}